#!/bin/bash

event_rotate='*code 7 (REL_DIAL), value*'
event_press='*code 256 (BTN_0), value 1*'
event_release='*code 256 (BTN_0), value 0*'

function listen {
  device=$1
  evtest "$device" | while read line; do
    case $line in
      ($event_rotate) handle_rotate "$line" ;;
      ($event_press) handle_press ;;
      ($event_release) handle_release ;;
    esac
  done
}

function handle_rotate {
  raw_value=$1
  value=$(echo $raw_value | sed 's/.*value\ \(\d*\)/\1/g')

  safe_exec "rotate_action" "$value"
}

function handle_press {
  safe_exec 'press_action'
}

function handle_release {
  safe_exec 'release_action'
}

# Some helpers

function safe_exec {
  fn=$1
  args=$2
  function_exists $fn && $fn $args || echo "'$fn' is not implemented"
}

function function_exists {
  declare -F "$1" > /dev/null
}

function time_ms_now {
  date +%s%N | cut -b1-13
}
