#!/bin/bash

event_rotate='*code 7 (REL_DIAL), value*'
event_press='*code 256 (BTN_0), value 1*'
event_release='*code 256 (BTN_0), value 0*'

function listen {
  device=$1
  evtest "$device" | while read line; do
    case $line in
      ($event_rotate) handle_rotate "$line" ;;
      ($event_press) handle_press ;;
      ($event_release) handle_release ;;
    esac
  done
}

function handle_rotate {
  input=$1
  value=$(echo $input | sed 's/.*value\ \(\d*\)/\1/g')
  echo "ROTATE: $value"

  safe_exec 'rotate_action'
}

function handle_press {
  echo "PRESSED"

  safe_exec 'press_action'
}

function handle_release {
  echo "RELEASED"

  safe_exec 'release_action'
}

function safe_exec {
  fn=$1
  function_exists $fn && $fn || echo "'$fn' is not implemented"
}

function function_exists {
  declare -F "$1" > /dev/null
}
